const ERROR_LEVEL_1 = 'ERROR_LEVEL_FATAL';
const ERROR_LEVEL_2 = 'ERROR_LEVEL_ERROR';
const ERROR_LEVEL_3 = 'ERROR_LEVEL_WARNING';
const ERROR_LEVEL_4 = 'ERROR_LEVEL_FUNCTIONAL';
const ERROR_LEVEL_5 = 'ERROR_LEVEL_INFORMATIONAL';
const ERROR_LEVEL_6 = 'ERROR_LEVEL_DEBUG';

module.exports = {
    ERROR_LEVEL_1: ERROR_LEVEL_1,
    ERROR_LEVEL_2: ERROR_LEVEL_2,
    ERROR_LEVEL_3: ERROR_LEVEL_3,
    ERROR_LEVEL_4: ERROR_LEVEL_4,
    ERROR_LEVEL_5: ERROR_LEVEL_5,
    ERROR_LEVEL_6: ERROR_LEVEL_6
};
